import { Protocol } from 'devtools-protocol'

export const FB_COOKIES: Protocol.Network.CookieParam[] = [
  {
    name: 'fr',
    value:
      '0q0f36MzrjXlBMyFN.AWUSY_xfpYeFN7h3RardU1uopcs.Bj_cvJ.bs.AAA.0.0.Bj_cvK.AWUrI14jHss',
    domain: '.facebook.com',
    path: '/',
    expires: 1685353158.647013,
    // size: 84,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'xs',
    value: '45%3ABzSHQs-iPrVfJg%3A2%3A1677577162%3A-1%3A11303',
    domain: '.facebook.com',
    path: '/',
    expires: 1709113161.646996,
    // size: 51,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'datr',
    value: 'ycv9Y4ZcR-mYosYzteNhJSQw',
    domain: '.facebook.com',
    path: '/',
    expires: 1712137162.170498,
    // size: 28,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'c_user',
    value: '100000236390565',
    domain: '.facebook.com',
    path: '/',
    expires: 1709113161.646978,
    // size: 21,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'wd',
    value: '800x600',
    domain: '.facebook.com',
    path: '/',
    expires: 1678181966,
    // size: 9,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'Lax',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'sb',
    value: 'ycv9Y5BbR3SsbUrHwJ98G0d2',
    domain: '.facebook.com',
    path: '/',
    expires: 1712137164.646931,
    // size: 26,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
]
