import { Protocol } from 'devtools-protocol'

export const FB_COOKIES: Protocol.Network.CookieParam[] = [
  {
    name: 'fr',
    value:
      '0OyAs7w3MZ0ftMQN9.AWVY0M6OU_vddOs4Z9TCiZr3z6M.BkDWAA.hX.AAA.0.0.BkDWAB.AWVpf237bSc',
    domain: '.facebook.com',
    path: '/',
    expires: 1686374143.165634,
    // size: 84,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'xs',
    value: '1%3AaSQTjCg6aHHZmw%3A2%3A1678598145%3A-1%3A11303',
    domain: '.facebook.com',
    path: '/',
    expires: 1710134145.165617,
    // size: 50,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'datr',
    value: 'AGANZJq3jv4SOSCEwezyrA7q',
    domain: '.facebook.com',
    path: '/',
    expires: 1713158145.683291,
    // size: 28,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'c_user',
    value: '100000236390565',
    domain: '.facebook.com',
    path: '/',
    expires: 1710134145.165594,
    // size: 21,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'wd',
    value: '800x600',
    domain: '.facebook.com',
    path: '/',
    expires: 1679202948,
    // size: 9,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'Lax',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'sb',
    value: 'AGANZJharDzDCW_8PYzXFNwY',
    domain: '.facebook.com',
    path: '/',
    expires: 1713158147.165546,
    // size: 26,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
]
